controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

arm_joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - ArmR1_Cla1
      - ArmR2_Sho1
      - ArmR3_Sho2
      - ArmR4_Sho3
      - ArmR5_Elb1
      - ArmR6_Elb2
      - ArmR7_Wrist_Hemisphere_A
      - ArmR8_Wrist_Hemisphere_B

    command_interfaces:
      - position
      # - velocity
      # - effort

    state_interfaces:
      - position
      - velocity

    open_loop_control: True

